name: Deploy AWS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - name: Clone do projeto
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then pytest; fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "henryidesis"
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: henryidesis/stocks-ci:${{ github.sha }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_KEY }}
          username: "ubuntu"
          key: ${{ secrets.TEST_KEY }}
          port: 22
          script: |
            docker stop stocks || true
            docker rm --force stocks || true
            docker run -d -p 8080:8080 --name stocks henryidesis/stocks-ci:${{ github.sha }}